# -*- coding: utf-8 -*-
"""Cleaning US Census Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HK9UVhluQDGY9TG6OjMq6uRGYD4nlkOz

#Cleaning US Census Data
"""

#Importing datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob

"""Using glob, loop through the census files available and load them into DataFrames. Then, concatenate all of those DataFrames together into one DataFrame"""

us_census = glob.glob('states*.csv')
df_list = []
for filename in us_census:
  data = pd.read_csv(filename)
  df_list.append(data)

df = pd.concat(df_list)

df.head()

#checking the columns in dataset
print(df.columns)

"""Use regex to turn the Income column into a format that is ready for conversion into a numerical type."""

df['Income'] = df.Income.replace('[/$]', '', regex=True)
df.head()

#converting the income column into numeric value
df.Income = pd.to_numeric(df.Income)
print(df.dtypes)

"""Look at the GenderPop column. We are going to want to separate this into two columns, the Men column, and the Women column."""

gender_split = df.GenderPop.str.split('_')
df['Men'] = gender_split.str.get(0)
df['Women'] = gender_split.str.get(1)

"""There is still an M or an F character in each entry! We should remove those before we convert."""

df['Men'] = df.Men.str[:-1]
df['Women'] = df.Women.str[:-1]
df.Men = pd.to_numeric(df.Men)
df.Women = pd.to_numeric(df.Women)
df.head()

#checking duplicates in state column
duplicates = df.duplicated(subset=['State'])
print(duplicates.value_counts())
#Drop those duplicates 
df = df.drop_duplicates()

plt.scatter(df.Women, df.Income)
plt.xlabel('Women')
plt.ylabel('Income')
plt.show()

print(df.columns)

#removing % sign and converting columns into numeric value
df['Hispanic'] = df.Hispanic.str[:-1]
df['Hispanic'] = pd.to_numeric(df.Hispanic)
df['White'] = df.White.str[:-1]
df['White'] = pd.to_numeric(df.White)
df['Black'] = df.Black.str[:-1]
df['Black'] = pd.to_numeric(df.Black)
df['Native'] = df.Native.str[:-1]
df['Native'] = pd.to_numeric(df.Native)
df['Asian'] = df.Asian.str[:-1]
df['Asian'] = pd.to_numeric(df.Asian)
df['Pacific'] = df.Pacific.str[:-1]
df['Pacific'] = pd.to_numeric(df.Pacific)

df = df.fillna(value={
'Hispanic': df.Hispanic.mean(),
'White': df.White.mean(),
'Black': df.Black.mean(),
'Native': df.Native.mean(),
'Asian': df.Asian.mean(),
'Pacific': df.Pacific.mean(),
})

plt.hist(df['Hispanic'])
plt.title('Hispanic')
plt.show()
plt.hist(df['White'])
plt.title('White')
plt.show()
plt.cla()

plt.hist(df['Black'])
plt.title('Black')
plt.show()
plt.cla()

plt.hist(df['Native'])
plt.title('Native')
plt.show()
plt.cla()

plt.hist(df['Pacific'])
plt.title('Pacific')
plt.show()
plt.cla()

plt.hist(df['Asian'])
plt.title('Asian')
plt.show()

print(df.head())
print(df.dtypes)